FROM python:3.8-slim

WORKDIR /app
COPY . /app/

RUN python get-pip.py
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "carpool.wsgi:application"]
